[package]
name = "fulytic-server"
version.workspace = true
edition.workspace = true

[dependencies]
fulytic-logic = { path = "../" }

pretty_env_logger = "0.5"

tokio.workspace = true
log.workspace = true
bytes.workspace = true
uuid.workspace = true
