[package]
name = "fulytic-core"
version.workspace = true
edition.workspace = true

[dependencies]
local-fmt.workspace = true

crossbeam.workspace = true
strum.workspace = true
uuid.workspace = true
anyhow.workspace = true
