[package]
name = "fulytic-core"
version.workspace = true
edition.workspace = true

[dependencies]
enum-table.workspace = true
local-fmt.workspace = true

uuid.workspace = true
anyhow.workspace = true
